# -*- mode: ruby -*-
# vi: set ft=ruby :

# Every Vagrant development environment requires a box. You can search for
# boxes at https://atlas.hashicorp.com/search.
BOX_IMAGE = "ubuntu/trusty32"

Vagrant.configure("2") do |config|
  config.vm.define "staging" do |subconfig|
    subconfig.vm.box = BOX_IMAGE
    subconfig.vm.hostname = "staging"
    subconfig.vm.network :private_network, ip: "192.168.68.10"
    subconfig.vm.network :forwarded_port, guest: 80, host: 8010
    subconfig.vm.provision :shell, :path => ".provision/bootstrap.sh"
  end

  config.vm.define "prod" do |subconfig|
    subconfig.vm.box = BOX_IMAGE
    subconfig.vm.hostname = "prod"
    subconfig.vm.network :private_network, ip: "192.168.68.11"
    subconfig.vm.network :forwarded_port, guest: 80, host: 8011
    subconfig.vm.provision :shell, :path => ".provision/bootstrap.sh"
  end

  # Install avahi on all machines
  config.vm.provision "shell", inline: <<-SHELL
    apt-get install -y avahi-daemon libnss-mdns
  SHELL
end
